### ISSUE TITLE
I need a GUI for this algorithm

### ISSUE THREAD

**Issue by vivek1117** [int-main/Quine-McCluskey#1]
Please provide me gui for this project and also include the no of variables to be entered
Please help me fast

**Comment by int-main** [comment]
@vivek1117 I created this program just for fun in my spare time. Currently I don't have time to implement the GUI for this program. Maybe, in future I might do it if I get time. You can implement the GUI yourself using Tk or Qt framework. The calculations are pretty straightforward and the final result is stored in "final_result" variable as a list.
